### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by edgarberlinck** [MentoriaApp/frontend#17]
O arquivo README está com o texto auto-gerado pelo React-Cli. Seria interessante escrever um pouco sobre o projeto, sugiro o seguinte:

  - O que o projeto faz
  - Projetos relacionados (Nosso backend, por exemplo e libs de terceiros)
  - Como buildar o projeto

Não precisa ser necessariamente isso tampouco nesta ordem. Estou aberto a sugestões.

**Comment by WendellAdriel** [comment]
Opa, se quiser posso abrir um PR, tenho costume de criar READMEs em projetos aqui no GH e nas empresas que trabalho

**Comment by edgarberlinck** [comment]
Por favor!
