### ISSUE TITLE
[Registro] Funcionalidades para Mentores

### ISSUE THREAD

**Issue by edgarberlinck** [MentoriaApp/frontend#3]
Foi reportado no grupo de mentores no Telegram a seguinte situação:

> O mentorado muitas vezes sai atirando pra todos os lados, isso acaba criando uma situação chata pois o mentor acaba ficando mal com isso, pois ele aceita mentorar a pessoa e se organiza pra isso e depois o mentorado some, pois a outra pessoa que ele procurou respondeu e também aceitou.

Este tipo de comportamento deve ser evitado no sistema. Vamos propor alguma coisa?

**Comment by edgarberlinck** [comment]
@maxdevjs 

Eu apenas faria uma mudança: Não creio que seja legal o mentorado requisitar vários mentores, o problema vai se repetir. Acredito que ele só possa solicitar uma mentoria por skill e aguardar o mentor responder.

Temos uma situação provável onde o mentror demore pra responder, então isso deve ser tratado também. Creio que é complicado definir um valor arbitrário, então podemos incluir um botão de "desistir", assim o mentorado pode solicitar outro mentor sem problemas.

Acho interessante logar todas essas ações, pois vai nos permitir dar uma nota para o mentor.

**Comment by maxdevjs** [comment]
@edgarberlinck sem muitas complicações, concordo. 

No entanto o intuito da proposta era mais dar uma certa margem de certeza para o mentorado ("agora sei que talvez precise esperar, mas estou dentro e vale a pena esperar"), caso contrário é fácil não ter ideia do que está acontecendo e se sentir frustrado, aka o mentorado requisitar vários mentores esperando receber alguma confirmação.

Quanto ao log, excelente idéia.

**Comment by edgarberlinck** [comment]
@maxdevjs

Essa situação é bem complicada, temos que achar um meio termos e equilibrar
o requisito para que fique bom para todos. Nesse caso acho que seria
interessante limitar a quantidade de requisições por skill. Podemos deixar
em 2 ou 3.

O que acha?

Em qui, 9 de ago de 2018 às 18:28, maxdevjs <notifications@github.com>
escreveu:

**Comment by maxdevjs** [comment]
@edgarberlinck 


ja' existe algo do tipo implementado no @training-center (e / ou em alguma outra iniciativa), ou seria prerrogativa do app? 

Sim, faz sentido o que apresentou. Pessoalmente estou olhando mais pelo lado do mentorado...

**Comment by maxdevjs** [comment]
Para eu me orientar melhor no tópico: qual seria a contra-indicação na ligação entre mentorado e um mentor específico?

**Comment by edgarberlinck** [comment]
Então, primeiro acho que devemos olhar tanto para o mentor quanto para o
mentorado. Isso é um ponto delicado.

A relação deles deve ser de professores e aluno, creio eu. Os moldes do
programa de mentoria do Traning Center é uma boa orientação.

O principal que deve ser tratado é o processo de escolha do mentor. Entendo
que ele, mentor, é uma pessoa rara de se achar, ainda mais de graça. Logo
receber um pedido e logo depois ter ele cancelado oq o aluno preferiu outro
é desmotivador. Temos que tomar cuidado com isso.

**Comment by maxdevjs** [comment]
Primeiramente, obrigado por dedicar seu tempo a esta disquisição filosófica.

Concordo com a necessidade de valorizar ambos.

Preciso checar o programa de mentoria do Traning Center...

Então o que deve ser discutido é o processo de escolha do mentor.
Nesse ponto me perco: nos casos em que é inevitável a troca (isso pode acontecer por várias razões, é a vida), não seria melhor ter transparência e procurar evitar frustrações para as partes?

**Comment by edgarberlinck** [comment]
Concordo.

>
Vamos deixar esse assunto mais pra frente, assim outras pessoas podem
opinar tbm.
