### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by edgarberlinck** [MentoriaApp/frontend#7]
A listagem de mentores está um pouco ruim, precisamos deixar o layout um pouco mais consistente.

**Comment by evaldosantos** [comment]
O que voce acha de usar uma lib de UI como o reactstrap ou semantic ui. Poderiamos usar cards para mostrar os mentores (https://react.semantic-ui.com/views/card/).

**Comment by edgarberlinck** [comment]
Você consegue fazer um PR com um componente desses?

Em qui, 15 de nov de 2018 13:18, Evaldo Santos <notifications@github.com
escreveu:

**Comment by danilogila** [comment]
caso o @evaldosantos não se importe, posso tentar implementar a soluçao que ele indicou.

**Comment by edgarberlinck** [comment]
Fique a vontade.

Em seg, 26 de nov de 2018 17:43, Danilo Gila de Santana <
notifications@github.com escreveu:

**Comment by edgarberlinck** [comment]
@danilogila Caso tenha alguma dúvida avise aqui por favor.
